# Generated by Django 4.2.5 on 2023-09-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condidatedata',
            name='cand_presslink',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='condidatedata',
            name='cand_priority',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='condidatedata',
            name='issues_facing',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='condidatedata',
            name='unique_strg',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='condidatedata',
            name='why_running',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='condidatedata',
            name='why_vote',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
