# Generated by Django 4.2.5 on 2023-09-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partydata',
            old_name='Founded_year',
            new_name='founded_year',
        ),
        migrations.RenameField(
            model_name='partydata',
            old_name='Founder',
            new_name='founder',
        ),
    ]
