# Generated by Django 4.2.5 on 2023-09-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionApp', '0002_condidatedata_cand_presslink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partydata',
            old_name='about_me',
            new_name='about_party',
        ),
        migrations.RenameField(
            model_name='partydata',
            old_name='founder',
            new_name='founder_1',
        ),
        migrations.RenameField(
            model_name='partydata',
            old_name='contact_details',
            new_name='founder_2',
        ),
        migrations.RemoveField(
            model_name='partydata',
            name='password',
        ),
        migrations.AddField(
            model_name='partydata',
            name='founder_3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='partydata',
            name='founder_4',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='partydata',
            name='party_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='partydata',
            name='party_contact_details',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='partydata',
            name='party_q_internation_relation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='partydata',
            name='party_q_introduce',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='partydata',
            name='party_q_performance',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='partydata',
            name='party_q_productivity',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='partydata',
            name='party_q_religious',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='partydata',
            name='party_q_terrorism',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='partydata',
            name='poling_avg',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='partydata',
            name='time_in_gov',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='partydata',
            name='party_logo',
            field=models.FileField(blank=True, default='', upload_to='media/'),
        ),
    ]
