# Generated by Django 4.2.5 on 2023-09-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electionApp', '0003_rename_about_me_partydata_about_party_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partydata',
            name='poling_avg',
        ),
    ]
