# Generated by Django 4.2.5 on 2023-09-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionApp', '0004_remove_partydata_poling_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='condidatedata',
            name='cand_img',
            field=models.FileField(blank=True, default='', upload_to='candidates/'),
        ),
    ]
